#show the output that would be generated by each of the following program fragments
#the output of this program will return the square of 1-11

import cmath;

def range1():

    for i in range(1,11):
        print(i*i)


range1()
